# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-17 19:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('structure', '0044_terms_of_services_url'),
        ('nodeconductor_cost_planning', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presetitem',
            name='default_price_list_item',
        ),
        migrations.RemoveField(
            model_name='presetitem',
            name='preset',
        ),
        migrations.RemoveField(
            model_name='deploymentplan',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='deploymentplan',
            name='object_id',
        ),
        migrations.AddField(
            model_name='deploymentplan',
            name='certifications',
            field=models.ManyToManyField(blank=True, to='structure.ServiceCertification'),
        ),
        migrations.AddField(
            model_name='preset',
            name='cores',
            field=models.PositiveIntegerField(default=0, help_text='Preset cores count.'),
        ),
        migrations.AddField(
            model_name='preset',
            name='ram',
            field=models.PositiveIntegerField(default=0, help_text='Preset ram amount in MB.'),
        ),
        migrations.AddField(
            model_name='preset',
            name='storage',
            field=models.PositiveIntegerField(default=0, help_text='Preset storage amount in MB.'),
        ),
        migrations.DeleteModel(
            name='PresetItem',
        ),
    ]
