# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-03-21 14:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nodeconductor_cost_planning', '0003_deployment_plan_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deploymentplan',
            name='customer',
        ),
        migrations.AlterField(
            model_name='deploymentplan',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='structure.Project'),
        ),
    ]
